### PR TITLE
chore(deps): bump @immobiliare/dats to 5.1.0

### PR DESCRIPTION
**Pull request by ryanrishi**
## 🚨 Proposed changes

> Please review the [guidelines for contributing](../../CONTRIBUTING.md) to this repository.

Pull in changes from https://github.com/immobiliare/dats/pull/922

Also noticed that `package-lock.json` and `yarn.lock` are in `.gitignore`— it's best practice to commit those files (per [npm](https://docs.npmjs.com/cli/v6/configuring-npm/package-locks), [yarn](https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/)) so that builds are consistent and reliable.

## ⚙️ Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply_

-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)
-   [ ] Refactor

### CODE REVIEW

**Comment by simonecorsi** [comment]
Hi @ryanrishi, can you please amend the commit to use conventional commit convention please? :)

**Review by dnlup — APPROVED** [review]
Thank you @ryanrishi for this. We have an issue with the @tapjs/sinon plugin , let's wait a bit to see if it gets fixed so the the tests will start working again.

**Comment by dnlup** [comment]
> Also noticed that package-lock.json and yarn.lock are in .gitignore— it's best practice to commit those files (per [npm](https://docs.npmjs.com/cli/v6/configuring-npm/package-locks), [yarn](https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/)) so that builds are consistent and reliable.

We decided to remove the lock file because a few Node majors ago those files had different version between Node version (because the shipped npm had different major versions) and that caused issues. Since lock files are ignored when a package it's installed as a lib, like this plugin is, we opted to live with the fact the local builds do not use a lock.

**Comment by dnlup** [comment]
@ryanrishi I managed to fix test errors and merged the fix, if you could change the commit message we would merge this and publish a new release 😉

**Pull request merged**
