### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by Zajozor**
## 🚨 Proposed changes

Just a small typo fix.

## ⚙️ Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply_

-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [x] Documentation Update (if none of the other choices apply)
-   [ ] Refactor

### CODE REVIEW

**Review by antoniomuso — APPROVED** [review]
Thank you!

**Comment by simonecorsi** [comment]
Sorry I've missed a thing in the review :pray:

We're using [convetional-commit](https://www.conventionalcommits.org/en/v1.0.0-beta.2/) to lint our commits, can you please rewrite the message so we can merge it? 😄 

You can use the following commands:
```sh
git commit --amend -m "docs(README.md): fix typo"
git push origin patch-1 -f
```

**Comment by Zajozor** [comment]
@simonecorsi I'm not sure why it took me over a month to do this 😅 Just got lost in the backlog, sorry.

I fixed the commit message, sorry for not reading the guidelines properly before :)

**Review by antoniomuso — APPROVED** [review]

**Comment by simonecorsi** [comment]
> @simonecorsi I'm not sure why it took me over a month to do this 😅 Just got lost in the backlog, sorry.
> 
> I fixed the commit message, sorry for not reading the guidelines properly before :)

Don't worry! It happens to me all the time! 😄 
Thanks for fixing it!

**Review by simonecorsi — APPROVED** [review]
🚀

**Pull request merged**
