### PR TITLE
test: migrate to tap

### PR DESCRIPTION
**Pull request by dnlup**

### CODE REVIEW

**Comment by dnlup** [comment]
I'll fix all conflicts 😉

**Comment by dnlup** [comment]
> I'll fix all conflicts 😉

Conflicts fixed, I would like to refactor a bit the latest changes.

**Comment by simonecorsi** [comment]
> Conflicts fixed, I would like to refactor a bit the latest changes.

@dnlup can you set this as Draft if you need to do more work so I don't merge by error?

**Comment by dnlup** [comment]
> > Conflicts fixed, I would like to refactor a bit the latest changes.
> 
> @dnlup can you set this as Draft if you need to do more work so I don't merge by error?

On second thought, I'll refactor in another PR. We can merge this.

**Pull request merged**
