### PR TITLE
feat(fastify): updated to v4

### LINKED ISSUE #229: Support fastify@4

### PR DESCRIPTION
**Pull request by simonecorsi**
closes #229

BREAKING CHANGES: fastify major update

### CODE REVIEW

**Comment by simonecorsi** [comment]
Tests are failing en masse, this needs some more work.

**Comment by simonecorsi** [comment]
TODO: Rewrite commit to have `BREAKING CHANGE` without `s`

**Comment by dnlup** [comment]
@simonecorsi I am still trying to understand why on tests we need to `await` the plugin registration, but we are onto something to make this work 😉 . I'll clean up everything soon.

**Comment by dnlup** [comment]
I couldn't figure out the reason for the different behaviour in tests, but using `await` is cited in some articles (as you pointed out) as a change migrating to version 4 (https://medium.com/@fastifyjs/fastify-v4-ga-59f2103b5f0e). I think we can move on and merge. I'll clean up my last commit 😉

**Comment by simonecorsi** [comment]
@dnlup should we update our example to use `await` when registering plugins?

**Comment by dnlup** [comment]
> @dnlup should we update our example to use `await` when registering plugins?

Updated the examples 😉

**Comment by dnlup** [comment]
> If this is done for you I'll add the new CI too!

Yeah, go ahead 😉

**Pull request merged**
