### PR TITLE
fix: fix fastify deprecation

### LINKED ISSUE #316: Handle fastify deprecation
The deprecation says we cannot access `context` from the `request` anymore in version 5

Schermata 2022-10-18 alle 14 05 06

### PR DESCRIPTION
**Pull request by dnlup**
## 🚨 Proposed changes

> Please review the [guidelines for contributing](../../CONTRIBUTING.md) to this repository.

In this MR we are fixing the Fastify deprecation that says we cannot access context from the request anymore in version 5

## ⚙️ Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply_

-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)
-   [ ] Refactor

Closes #316 

/cc @mdoria12

### CODE REVIEW

**Comment by antoniomuso** [comment]
Can you put what are the deprecations did by fastify?

**Comment by mdoria12** [comment]
LGTM

**Comment by dnlup** [comment]
> Can you put what are the deprecations did by fastify?

Where do you want to put them?

**Comment by dnlup** [comment]
I have updated the the MR description 😉

**Review by simonecorsi — APPROVED** [review]

**Pull request merged**
